### ISSUE TITLE
API cuts off at hyperlink

### ISSUE THREAD

**Issue by SuwusanZ** [sandipbgt/theastrologer-api#2]
hey, i just wanted to let you know that whenever theres a hyperlink along with the horoscope of the day and so on, the api cuts off as soon as it reaches the hyperlink.

**Comment by sandipbgt** [comment]
Can you provide some more details? screenshots or examples etc.

**Comment by SuwusanZ** [comment]
Thank you for your quick response!

Here are some of the examples we received after running your API through
our simulator and also Postman. The horoscope text results from the API
call cut off after any hyperlinked word. Please see the attached screen
grabs.

**Comment by sandipbgt** [comment]
Where are the screenshots ?

**Comment by SuwusanZ** [comment]
[image: Inline image 1][image: Inline image 5][image: Inline image 4][image:
Inline image 2][image: Inline image 3]

**Comment by sandipbgt** [comment]
I can't see the image. Can you see the preview after commenting ? Please preview the comment before commenting.

**Comment by SuwusanZ** [comment]
Sorry, I am unclear as to what you mean "preview after commenting"? Please
see the attached are the images/screengrabs once more below

Thank you.

[image: Inline image 5][image: Inline image 4][image: Inline image 3][image:
Inline image 2]
[image: Inline image 1]
