### ISSUE TITLE
Its not working :(

### ISSUE THREAD

**Issue by MalikQasimAli** [sandipbgt/theastrologer-api#6]
It says application error. Please fix the issue.

**Comment by primayudantra** [comment]
i think you can check my repo https://github.com/primayudantra/astrologer-api-horoscope, i created for scrapping astrologer.

**Comment by sandipbgt** [comment]
Please check these links.
http://sandipbgt.com/theastrologer-api/
http://sandipbgt.com/theastrologer/api/
