### ISSUE TITLE
It's not working again. 

### ISSUE THREAD

**Issue by themartinsjoseph** [sandipbgt/theastrologer-api#7]
It looks like it just requires some debugging with Heroku. Thank you for this service!

**Comment by primayudantra** [comment]
i think you can check my repo https://github.com/primayudantra/astrologer-api-horoscope, i created for scrapping astrologer.

**Comment by sandipbgt** [comment]
Please check these links.
http://sandipbgt.com/theastrologer-api/
http://sandipbgt.com/theastrologer/api/

**Comment by primayudantra** [comment]
thanks @sandipbgt !
